// GENERATED by tests/unit/balance/ttkBands.test.ts from the human TTK model (tests/unit/balance/ttkModel.ts):
// a mid-skill human vs a 400 HP hero strafing at 5 m/s, unarmored, 20 % headshots, the better of hip and ADS;
// seconds, Infinity = cannot down it in 12 s. Do not edit — regenerate with
//   UPDATE_TTK=1 npx vitest run tests/unit/balance/ttkBands.test.ts
export const WEAPON_TTK: Record<string, { m5: number; m20: number; m50: number }> = {
  pistol: { m5: 3.13, m20: 3.44, m50: 10.73 },
  carbine: { m5: 2.46, m20: 2.46, m50: 6.03 },
  smg: { m5: 2.07, m20: 2.71, m50: Infinity },
  zhuge: { m5: 1.84, m20: 2.95, m50: Infinity },
  qinggang: { m5: 3.01, m20: 3.01, m50: 3.77 },
  cixiong: { m5: 2.3, m20: 3.01, m50: Infinity },
  hanbing: { m5: 2.46, m20: 2.59, m50: 6.03 },
  guding: { m5: 1.58, m20: 8.27, m50: Infinity },
  qinglong: { m5: 2.06, m20: 2.19, m50: 4.06 },
  zhangba: { m5: 1.43, m20: 9.57, m50: Infinity },
  guanshi: { m5: Infinity, m20: 3.63, m50: 9.92 },
  zhuque: { m5: 1.81, m20: Infinity, m50: Infinity },
  fangtian: { m5: 2.55, m20: 4.35, m50: Infinity },
  qilin: { m5: 3.4, m20: 3.4, m50: 3.4 },
  longdan: { m5: 2.13, m20: 2.19, m50: 3.82 },
  liegong: { m5: 3.56, m20: 3.66, m50: 7.92 },
  jinfan: { m5: 1.93, m20: 2.64, m50: Infinity },
  xiaoji: { m5: 2.64, m20: 3.33, m50: 7.97 },
  taiping: { m5: 2.13, m20: 2.57, m50: 10.08 },
  wushuang: { m5: 2.19, m20: 2.39, m50: 3.99 },
  huben: { m5: 2.67, m20: 2.9, m50: 5.67 },
  qingnang: { m5: 2.63, m20: 3.01, m50: 7.59 },
  yitian: { m5: 3.01, m20: 3.01, m50: 3.41 },
  hutou: { m5: 2.15, m20: 2.34, m50: 5.66 },
  jiguan: { m5: 2, m20: 2.18, m50: 5.96 },
  manwang: { m5: 1.53, m20: 10.25, m50: Infinity },
  baiyi: { m5: 2.64, m20: 2.64, m50: 3.41 },
};
