// GENERATED by tests/unit/balance/ttkBands.test.ts from the human TTK model (tests/unit/balance/ttkModel.ts):
// a mid-skill human vs a 400 HP hero strafing at 5 m/s, unarmored, 20 % headshots, the better of hip and ADS;
// seconds, Infinity = cannot down it in 12 s. Do not edit — regenerate with
//   UPDATE_TTK=1 npx vitest run tests/unit/balance/ttkBands.test.ts
export const WEAPON_TTK: Record<string, { m5: number; m20: number; m50: number }> = {
  pistol: { m5: 3.13, m20: 3.45, m50: 10.76 },
  carbine: { m5: 2.49, m20: 2.62, m50: 6.06 },
  smg: { m5: 2.07, m20: 2.72, m50: Infinity },
  zhuge: { m5: 1.84, m20: 2.96, m50: Infinity },
  qinggang: { m5: 3.05, m20: 3.05, m50: 3.81 },
  cixiong: { m5: 2.3, m20: 2.95, m50: Infinity },
  hanbing: { m5: 2.49, m20: 2.62, m50: 6.06 },
  guding: { m5: 1.61, m20: 8.33, m50: Infinity },
  qinglong: { m5: 2.09, m20: 2.22, m50: 4.09 },
  zhangba: { m5: 1.43, m20: 9.63, m50: Infinity },
  guanshi: { m5: Infinity, m20: 3.63, m50: 10 },
  zhuque: { m5: 1.81, m20: Infinity, m50: Infinity },
  fangtian: { m5: 2.55, m20: 4.39, m50: Infinity },
  qilin: { m5: 3.5, m20: 3.5, m50: 3.5 },
  longdan: { m5: 2.13, m20: 2.22, m50: 3.85 },
  liegong: { m5: 3.65, m20: 3.75, m50: 8.1 },
  jinfan: { m5: 1.93, m20: 2.65, m50: Infinity },
  xiaoji: { m5: 2.73, m20: 3.42, m50: 8.68 },
  taiping: { m5: 2.13, m20: 2.6, m50: 10.02 },
  wushuang: { m5: 2.2, m20: 2.42, m50: 4.02 },
  huben: { m5: 2.73, m20: 2.96, m50: 5.62 },
  qingnang: { m5: 2.63, m20: 2.75, m50: 7.61 },
  yitian: { m5: 3.05, m20: 3.05, m50: 3.45 },
  hutou: { m5: 2.15, m20: 2.37, m50: 5.46 },
  jiguan: { m5: 2, m20: 2.2, m50: 6 },
  manwang: { m5: 1.53, m20: 10.46, m50: Infinity },
  baiyi: { m5: 2.68, m20: 2.91, m50: 3.71 },
};
